# Generated by tools/render_packages.py from packaging/homebrew/jai.rb.tmpl in
# https://github.com/matteopolak/jai for release v0.5.1. Do not edit by hand.
class Jai < Formula
  desc "Independent toolchain for the Jai language: compiler, LSP, linter and formatter"
  homepage "https://github.com/matteopolak/jai"
  # Plus the jaic Runtime Library Exception (LICENSE-EXCEPTION), which has no SPDX identifier.
  license "AGPL-3.0-or-later"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # Releases after 0.4.1 have a build for each of these. For 0.4.1 and earlier,
  # tools/render_packages.py gives Intel macOS and arm64 Linux the URL of the nearest build, so the
  # formula still loads there, and adds `depends_on arch:` lines that refuse the install there.
  on_macos do
    on_arm do
      url "https://github.com/matteopolak/jai/releases/download/v0.5.1/jai-macos-arm64.tar.gz"
      sha256 "61789b22c6aca872a8459663aed4e45d0f191b7e30ea1b91b878abce57d95447"
    end
    on_intel do
      url "https://github.com/matteopolak/jai/releases/download/v0.5.1/jai-macos-x64.tar.gz"
      sha256 "890852b9f244e113e19bd7b036da8e8086f298f7a11512981acbd5af41879759"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/matteopolak/jai/releases/download/v0.5.1/jai-linux-arm64.tar.gz"
      sha256 "844ce6fce2527901c2b8861130de262b30b1571fbc558448099fabfab8a7b9c5"
    end
    on_intel do
      url "https://github.com/matteopolak/jai/releases/download/v0.5.1/jai-linux-x64.tar.gz"
      sha256 "eade01fe0cab683866de92f1ffa61c4fb6f3316a2ef6e8f7a17105af651ad1a4"
    end
  end

  def install
    # jaic, jailint and jailsp find stdlib/ (which loads ../prelude/) next to the real file
    # behind the bin/ symlinks, and native libraries (wgpu-native, stb_*, rpmalloc) in
    # ../artifacts/native-libs. Archives up to 0.4.0 have no artifacts/.
    libexec.install "jaic", "jailsp", "jailint", "jaifmt", "stdlib", "prelude"
    libexec.install "artifacts" if File.directory?("artifacts")
    bin.install_symlink libexec/"jaic", libexec/"jailsp", libexec/"jailint", libexec/"jaifmt"
    doc.install "README.md", "CHANGELOG.md"
  end

  test do
    (testpath/"hello.jai").write <<~JAI
      #import "Basic";

      main :: () {
          print("Hello from Homebrew!\\n");
      }
    JAI
    assert_equal "Hello from Homebrew!\n", shell_output("#{bin}/jaic run hello.jai")
    assert_equal "main :: () {\n    x := 1;\n}\n", pipe_output("#{bin}/jaifmt --stdin", "main::(){x:=1;}")
    system bin/"jailint", "hello.jai"
  end
end
