# Generated by tools/render_packages.py from packaging/homebrew/jai.rb.tmpl in
# https://github.com/matteopolak/jai for release v0.4.0. Do not edit by hand.
class Jai < Formula
  desc "Independent toolchain for the Jai language: compiler, LSP, linter and formatter"
  homepage "https://github.com/matteopolak/jai"
  # Plus the jaic Runtime Library Exception (LICENSE-EXCEPTION), which has no SPDX identifier.
  license "AGPL-3.0-or-later"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # Releases ship macOS arm64 and Linux x86-64 builds only (LLVM publishes no Intel macOS build
  # of LLVM 23). The other platforms get the URL of the nearest build so the formula still loads
  # there, and `depends_on arch:` refuses the install with a clear message.
  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/matteopolak/jai/releases/download/v0.4.0/jaic-macos-arm64.tar.gz"
      sha256 "804f57524a0e41aa704a71acd2bb2293e5f07ff7b81321bfa1fbc9a0f2cafc21"
    end
    on_intel do
      url "https://github.com/matteopolak/jai/releases/download/v0.4.0/jaic-macos-arm64.tar.gz"
      sha256 "804f57524a0e41aa704a71acd2bb2293e5f07ff7b81321bfa1fbc9a0f2cafc21"
    end
  end

  on_linux do
    depends_on arch: :x86_64

    on_arm do
      url "https://github.com/matteopolak/jai/releases/download/v0.4.0/jaic-linux-x64.tar.gz"
      sha256 "264dd5ca258a36da1368c53b16c375bd572aaf922aa9a29cd97224f2829289de"
    end
    on_intel do
      url "https://github.com/matteopolak/jai/releases/download/v0.4.0/jaic-linux-x64.tar.gz"
      sha256 "264dd5ca258a36da1368c53b16c375bd572aaf922aa9a29cd97224f2829289de"
    end
  end

  def install
    # jaic, jailint and jailsp find stdlib/ (which loads ../prelude/) next to the real file
    # behind the bin/ symlinks.
    libexec.install "jaic", "jailsp", "jailint", "jaifmt", "stdlib", "prelude"
    bin.install_symlink libexec/"jaic", libexec/"jailsp", libexec/"jailint", libexec/"jaifmt"
    doc.install "README.md", "CHANGELOG.md"
  end

  test do
    (testpath/"hello.jai").write <<~JAI
      #import "Basic";

      main :: () {
          print("Hello from Homebrew!\\n");
      }
    JAI
    assert_equal "Hello from Homebrew!\n", shell_output("#{bin}/jaic run hello.jai")
    assert_equal "main :: () {\n    x := 1;\n}\n", pipe_output("#{bin}/jaifmt --stdin", "main::(){x:=1;}")
    system bin/"jailint", "hello.jai"
  end
end
