# Generated by tools/render_packages.py from packaging/homebrew/jai.rb.tmpl in
# https://github.com/matteopolak/jai for release v0.4.2. Do not edit by hand.
class Jai < Formula
  desc "Independent toolchain for the Jai language: compiler, LSP, linter and formatter"
  homepage "https://github.com/matteopolak/jai"
  # Plus the jaic Runtime Library Exception (LICENSE-EXCEPTION), which has no SPDX identifier.
  license "AGPL-3.0-or-later"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # Releases after 0.4.1 have a build for each of these. For 0.4.1 and earlier,
  # tools/render_packages.py gives Intel macOS and arm64 Linux the URL of the nearest build, so the
  # formula still loads there, and adds `depends_on arch:` lines that refuse the install there.
  on_macos do
    on_arm do
      url "https://github.com/matteopolak/jai/releases/download/v0.4.2/jai-macos-arm64.tar.gz"
      sha256 "37c9259eae9dacf1f81b95544cc7d206af1f3fdda8c5f899d7f497dee0562626"
    end
    on_intel do
      url "https://github.com/matteopolak/jai/releases/download/v0.4.2/jai-macos-x64.tar.gz"
      sha256 "d62e84aa198482e821a0c7fa71e0d47881a21602f75781bf9c32c9a87f80251c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/matteopolak/jai/releases/download/v0.4.2/jai-linux-arm64.tar.gz"
      sha256 "a6adb27541c07783f70447b48ceae2f6135bb0443929dd4886512997db271927"
    end
    on_intel do
      url "https://github.com/matteopolak/jai/releases/download/v0.4.2/jai-linux-x64.tar.gz"
      sha256 "5fca9ad96e8b8eeb988ccc6f6789b1bb03d4e683431a9539f9b677cdc164f98d"
    end
  end

  def install
    # jaic, jailint and jailsp find stdlib/ (which loads ../prelude/) next to the real file
    # behind the bin/ symlinks, and native libraries (wgpu-native) in ../artifacts/native-libs.
    # Archives up to 0.4.0 have no artifacts/.
    libexec.install "jaic", "jailsp", "jailint", "jaifmt", "stdlib", "prelude"
    libexec.install "artifacts" if File.directory?("artifacts")
    bin.install_symlink libexec/"jaic", libexec/"jailsp", libexec/"jailint", libexec/"jaifmt"
    doc.install "README.md", "CHANGELOG.md"
  end

  test do
    (testpath/"hello.jai").write <<~JAI
      #import "Basic";

      main :: () {
          print("Hello from Homebrew!\\n");
      }
    JAI
    assert_equal "Hello from Homebrew!\n", shell_output("#{bin}/jaic run hello.jai")
    assert_equal "main :: () {\n    x := 1;\n}\n", pipe_output("#{bin}/jaifmt --stdin", "main::(){x:=1;}")
    system bin/"jailint", "hello.jai"
  end
end
